  1.  SQUARE
n=int(input("Enter the  value of n: "))
for i in range (n):
  for j in range (n):
   print("*",end="")
  print() 
   2.   1  TO  5 STAR
n=int(input("Enter the  value  of n: "))
for i in range (n):
  for j in range (i+1):
   print("*",end="")
  print()
    3. 5  to 1 star
 n=int(input("Enter the  value  of  n: "))
for i in range(n,0,-1):
  for j in range(i) :
   print("*",end="")
  print()

 

